### ISSUE TITLE
Angular can be improved

### ISSUE THREAD

**Issue by CKGrafico** [CKGrafico/papanasi#19]
Angular is not working well in the demos https://codesandbox.io/s/papanasi-angular-7bzn8h

How to solve: Create a demo were angular works.

**Comment by CKGrafico** [comment]
Angular is working now, but could be better

**Comment by DavidCMeier** [comment]
Maybe I could be created a Module for each component, for improve the imports inside the root module.

**Comment by DavidCMeier** [comment]
And in Angular, probably if you have the directive pa-button you don't need to create the button. So with that you only need to create the module with the directive.
