### ISSUE TITLE
Add the Qwik Framework

### ISSUE THREAD

**Issue by mhevery** [CKGrafico/papanasi#49]
Hello,

Qwik is now ready in mitosis! Could we kindly request that it would be added to Papanasi?

-- Misko

**Comment by CKGrafico** [comment]
Let's do this.

**Comment by mhevery** [comment]
💪

**Comment by CKGrafico** [comment]
Pending of https://github.com/BuilderIO/qwik/issues/1558

**Comment by CKGrafico** [comment]
We can say that this is done, not perfect yet but working.

Interesting for the future:
- https://github.com/simple-icons/simple-icons/issues/7922
- SSR
- Codesandbox instead of stackblitz
