### ISSUE TITLE
Storybook broken when click on "show code"

### ISSUE THREAD

**Issue by dimaslz** [CKGrafico/papanasi#64]
**Describe the bug**
Code examples in Storybook are broken

**To Reproduce**
- Go to https://papanasi.js.org/?path=/docs/%F0%9F%A7%A9elements-layout-container--container for example
- Click on "Show code" close to the view example
- You can see how all code examples is moving to:
  ```
  [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
  ```

If you click on "Hide code" again, it is not fixed, you need to reload the page. 

**Expected behavior**
Click on the "Show code" button close to view examples, should brake the code examples.

**Screenshots**
![CleanShot 2022-10-22 at 10 40 16](https://user-images.githubusercontent.com/1536936/197329976-a9a2db58-8a00-4be9-a222-a723dffe9be0.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 106.0.5249.119

**Comment by CKGrafico** [comment]
Thanks for the issue I’ve seen it some days ago and I’m still investigating. This is happening only on the first render (when F5) if you use the navigation menu is not happening

**Comment by CKGrafico** [comment]
Not happening anymore right? https://papanasi.js.org/?path=/docs/%F0%9F%A7%A9elements-components-avatar--avatar
