### ISSUE TITLE
Couldn't find story - "preview element" buttons are broken

### ISSUE THREAD

**Issue by milahu** [CKGrafico/papanasi#65]
**Describe the bug**
"preview element" buttons are broken

**To Reproduce**
in the readme https://github.com/CKGrafico/papanasi#-elements-showcase
click the "preview element" button for component X
next page says "Couldn't find story matching 'X'."

**Comment by CKGrafico** [comment]
Wow really good catch, fixed and deploying thanks!

**Comment by CKGrafico** [comment]
again :)
