### ISSUE TITLE
Inspirational libraries

### ISSUE THREAD

**Issue by CKGrafico** [CKGrafico/papanasi#7]
https://evergreen.segment.com/
https://ant.design/

**Comment by KalanaPerera** [comment]
Brother, Your idea is great, Thank you for creating this. 

Let us know how we can contribute, 

Take MUI also as an Inspirational library. -> https://mui.com/

--------------------------------

My thoughts. (Currently experiencing this problem)

1. We have a lot of CSS libraries, like Material Design, TailwindCss, Bootstrap, and many libraries.

I think we could create core component functionalities, which can plug with any CSS framework. I am not exactly sure Papanansi is the same idea. I just shared my thoughts. Available for brainstrome. **

**Comment by CKGrafico** [comment]
Thanks for your comments, my plan right now is to be able to bring a version with 0 styles and let the user be able to style everything they wanted.

más you will see every element in the dom comes with a BEM selector and all the colors and more variables are CSS custom properties

**Comment by CKGrafico** [comment]
@KalanaPerera I'm starting to add bugs with thelp wanted, maybe them inspire you.

**Comment by KalanaPerera** [comment]
> @KalanaPerera I'm starting to add bugs with help wanted, maybe them inspire you.

Sure, I will have a look. thanks for letting me know.
