### ISSUE TITLE
Docs: Link to pill from introduction page is broken

### ISSUE THREAD

**Issue by alexonaci** [CKGrafico/papanasi#79]
**Docs: Link to pill from introduction page is broken**
When navigating to the pill element from the introduction page -> elements showcase seems like the link is broken

**To Reproduce**
1. Go to https://papanasi.js.org/?path=/docs/%F0%9F%93%97documentation-introduction--page
2. Click on the pill 'Preview Element button'
5. See error
<img width="1358" alt="Screenshot 2023-04-18 at 23 02 00" src="https://user-images.githubusercontent.com/13402762/232892096-f6ad45b2-f0be-4740-8e69-d8c40bea4cf2.png">

**Expected behavior**
Page should render pill docs https://papanasi.js.org/?path=/docs/%F0%9F%A7%A9elements-components-pill--pill

- [x] Will add a fix

**Comment by CKGrafico** [comment]
Thanks for the change :)
